export default {
  BeritaCrypto: "Berita Crypto",
  Cryptocium: "Cryptocium",
  StressCapital: "Stress Capital",
  XDegods: "X+Degods",
  Claynocapital: "Claynocapital",
  DeadkingSociety: "DeadkingSociety",
  PestDAO: "Pest DAO",
  EnigmaVentures: "Enigma Ventures",
  PlayMaker: "PlayMaker",
  PaceCrypto: "Pace Crypto",
  RepublikRupiah: "Republik Rupiah",
  AirdropfindX: "AirdropfindX",
  Unidentified: "Unidentified",
  Solana100XHunt: "Solana 100X Hunt",
  TheEmpire: "The Empire",
  SniperDAO: "SniperDAO",
  MidaDAO: "Mida DAO",
  GhostKid: "Ghost Kid",
  SolhubDAO: "Solhub DAO",
  KinshuHUB: "Kinshu HUB",
  BAYCSG: "BAYC SG",
  Cryptic: "Cryptic",
  CCG: "C.C.G",
  YogurtVerse: "YogurtVerse",
  ShockedTrading: "Shocked Trading",
  PumpfunTrenches: "Pumpfun Trenches",
  ProsperityDAO: "Prosperity DAO",
  Versus: "Versus",
  HeavenorHell: "Heaven or Hell",
  Pastel: "Pastel",
  Sovereign: "Sovereign",
  FirstCumInside: "First Cum Inside",
  Sauce: "Sauce",
  TheTraphouse: "The Traphouse",
  GrandFNF: "Grand FNF",
  CookerFNF: "Cooker FNF",
  DegenerateNews: "Degenerate News",
  SyndicateNTWRK: "SyndicateNTWRK",
  Blocksmiths: "Blocksmiths",
  ZeroAttitude: "Zero Attitude",
  CryptoGalaxy: "Crypto Galaxy",
  Cryptostocks: "Cryptostocks"
} as Record<string, string>;
